### ISSUE TITLE
Calculated distance, time, etc. is based on data with outliers

### ISSUE THREAD

**Issue by peterdesmet** [inbo/gulltracking#13]
Some calculated fields use the previous record to calculate something:

* [calc_time_diff](https://github.com/inbo/bird-tracking-etl/blob/26dfffa7b0e19bb7bd9e8206d0cff1f44723ac29/R/enrich.R#L124)
* [calc_distance_diff](https://github.com/inbo/bird-tracking-etl/blob/26dfffa7b0e19bb7bd9e8206d0cff1f44723ac29/R/enrich.R#L145)
* [calc_speed2d](https://github.com/inbo/bird-tracking-etl/blob/26dfffa7b0e19bb7bd9e8206d0cff1f44723ac29/R/enrich.R#L169)

These calculations are done however BEFORE outliers are flagged. It might be better to calculate those excluding outliers to avoid odd values.

**Comment by peterdesmet** [comment]
Yes! And the outliers based on the criteria in step 3 will probably be smaller due to excluding some weird records in 1. So that's a bonus. Curious about the number of outliers in step 3 actually.

**Comment by peterdesmet** [comment]
In fact, maybe we should skip step 3 for now and see how many of those records we have.

**Comment by Wouter-Vansteelant** [comment]
This filter seems appropriate and useful to me. Until now I have never flagged outliers using altitude and accuracy. The thresholds you used here are, however, very liberal and won't lead to exhessive loss of data for the purpose of analyzing 2D flight statistics. The caveat, however, being that flight altitudes will still vary greatly in reliability within the selected range! That should be very clear to all potential users.

Filtering based on trajectory speeds has been satisfactory for most of my work until now, and I suspect also for the marsh harrier work we have planned.  I would, however, re-iterate the same speed filter two-three times, iteratively flagging points where either forward or backward trajectory speed (i.e. speed from point i to i+1 and from i-1 to i) exceeds a threshold of approx. 30 m/s

**Comment by peterdesmet** [comment]
@Wouter-Vansteelant would it be better to only flag on speed?

**Comment by Wouter-Vansteelant** [comment]
@peterdesmet I think it would be sufficient to do so. In the analyses I have done so far I applied the same speed filter twice (using a threshold of 30 m/s) before calculating final speeds.

**Comment by peterdesmet** [comment]
Great! @stijnvanhoey let's implement it like this. If you need to discuss the details, let me know.

**Comment by peterdesmet** [comment]
This applies to the [BirdTrackingEtl](https://github.com/inbo/gulltracking/releases/tag/bt-etl) version of the package, which we no longer maintain. Closing with `wontfix`.
