### ISSUE TITLE
Do we need hardcoded versions for dependencies?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/gulltracking#19]
See:

https://github.com/inbo/uvabits/blob/f8b1730b467729d99827f49799db450a507442c7/DESCRIPTION#L22-L32

Do these need hardcoded versions and if so, for which ones (e.g. I don't think we need it for knitr)? `devtools::check()` fails on my computer because:

```
namespace ‘data.table’ 1.11.8 is being loaded, but == 1.9.6 is required
```

**Comment by stijnvanhoey** [comment]
As we tend to have a package in continuous development for the entire community, we should remove these hard coded versions... But, we will have to check this before removing, as the monthly bird tracking pipeline relies on these versions (and we still run into troubles now and then). 

First thoughts: Removing versions here will actually induce issues:
- when features are added which are not supported by the defined pipeline R package versions
- when certain minimum versions are requested in this package, the installation in the pipeline will stop with an error

If we do not do the latter and we do not alter the functions used by the pipeline, this could(!) work in the short run but I'm worried about the long term aspect of it. Hence, we should make sure:
- the pipeline can use/install the package requirements of this package
- other R code in the pipeline should work with these versions as well

So, let's make sure to have a robust CI-check on the pipeline commands integrated in the adopted package setup?

**Comment by peterdesmet** [comment]
I have updated the hardcoded versions (`==`) to minimum versions (`>=`) for all dependencies in 34aa233. That allows easier development, e.g. running `devtools::check()` with more updated versions installed.

For the current pipeline, I have created a release of the package: https://github.com/inbo/uvabits/releases/tag/bt-etl

**Comment by peterdesmet** [comment]
This applies to the [BirdTrackingEtl](https://github.com/inbo/gulltracking/releases/tag/bt-etl) version of the package, which we no longer maintain. Closing with `wontfix`.
