### ISSUE TITLE
Add functionalities of append.metadata.R to this package

### ISSUE THREAD

**Issue by damianooldoni** [inbo/gulltracking#23]
As decided today with Jan Baert, @peterdesmet and Reinoud Allaert we are going to move the functionality in the R scripts in private repo: https://github.com/BelgiumLifeWatchGulltracking/Data_preprocessing into this R package.

We decided to start with the functionality in [`append.metadata.R`](https://github.com/BelgiumLifeWatchGulltracking/Data_preprocessing/blob/main/append.metadata.R)

**Comment by damianooldoni** [comment]
To do so, we are going to write:

- [ ] function in a R file in `./R` folder
- [ ] tests in `./tests`
- [ ] documentation in Roxygen2 format

**Comment by damianooldoni** [comment]
based on documentation of [`append.metadata()`](https://github.com/BelgiumLifeWatchGulltracking/Data_preprocessing) and online documentation of Movebank (https://www.movebank.org/cms/movebank-content/mb-data-model), I would rename  `meta.data` as `reference_data` and `GPS.data` as `event_data`. @peterdesmet: am I correct doing so?

**Comment by peterdesmet** [comment]
Yes, please rename. I would use:

- `reference_data` (`reference-data` in export, but underscore for parameter is better)
- `gps` (`event` is also used for acceleration data, so not good to differentiate)
- `acceleration`

Cf. how data are exported from Movebank and uploaded to Zenodo: https://doi.org/10.5281/zenodo.3968687

**Comment by damianooldoni** [comment]
Function does two things: 
1. adds the `reference_data`'s columns below to `gps` by joining on (`"tag-local-identifier"` = `"tag-id"`)
- `"animal-taxon"`
- `"animal-comments"`
- `"animal-life-stage"`
- `"animal-mass"`
- `"animal-ring-id"`
- `"animal-sex"`
- `"deployment-comments"`
2. rename them as:
species_name = "animal-taxon",
           bird_nickname = "animal-comments",
           stage = "animal-life-stage",
           weight = "animal-mass",
           colour_ring = "animal-ring-id",
           sex = "animal-sex",
           tag_location = "deployment-comments"

About the selection of the columns to join, I use a function argument, `reference_cols` with default value:
``` r
function(
  gps,
  reference_data,
  reference_cols = c(
    "tag-id",
    "animal-taxon",
    "animal-comments",
    "animal-life-stage",
    "animal-mass",
    "animal-ring-id",
    "animal-sex",
    "deployment-comments")
)
```

About renaming, I would do the same, by adding another default argument with the column names the use wants to give. @peterdesmet: do you agree?

**Comment by peterdesmet** [comment]
Quick feedback already before I review further: join should be done on 2 fields, since some tags are reused:

```
gps."tag-local-identifier" = ref."tag-id"
AND gps."individual-local-identifier" = ref."animal-id"
```

**Comment by peterdesmet** [comment]
1. Agree on the `reference_cols` argument.

2. I would simply not rename any column names. All names are defined by Movebank, so makes little sense to me to rename them, that also drops the requirement for an extra rename parameter

3. However, since some columns will be duplicates (sometimes under different names), I would only retain one:

- `animal-taxon` instead of `individual-taxon-canonical-name`
- `tag-id` instead of `tag-local-identifier`
- `animal-id` instead of `individual-local-identifier`

Since the last 3 columns of gps are:

```
individual-taxon-canonical-name = Larus fuscus
tag-local-identifier = 858
individual-local-identifier = L907004
```

I would drop those, but add the first 3 columns of the appended reference data in the **same order by default**, and then continue with the rest of the reference data:

```
animal-taxon = Larus fuscus
tag-id = 858
animal-id = L907004
...
animal-comments = Jasmin
```

**Comment by damianooldoni** [comment]
If the info in `animal-taxon` (in `reference`) and `individual-taxon-canonical-name` (in `gps`) are identical why not joining on it too? This way "dropping" is not needed and all is neat and easier to document. @peterdesmet: do you agree?

**Comment by peterdesmet** [comment]
Yes, that is fine. As long as the names we want to retain stay after the join.
