### ISSUE TITLE
Remove unused GitHub actions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/gulltracking#30]
I see some what look like some unused GitHub actions in https://github.com/inbo/gulltracking/tree/main/.github/workflows. These should be removed.

**Comment by damianooldoni** [comment]
If I check the actions run I see the following:

## test coverage
6 workflow runs
https://github.com/inbo/gulltracking/actions/workflows/test-coverage.yaml

## pkgdown
4 workflow runs
https://github.com/inbo/gulltracking/actions/workflows/pkgdown.yaml

## R-CMD-check
11 workflow run
https://github.com/inbo/gulltracking/actions/workflows/R-CMD-check.yaml

## Commands
1 workflow run
https://github.com/inbo/gulltracking/actions/workflows/pr-commands.yaml

Probably you referred to this last one, which is the one linked to the PR commands /document and /style? Indeed, no workflow runs were found. I just added a last comment (https://github.com/inbo/gulltracking/pull/29#issuecomment-823512704) and the workflow run started. You can see that an automatic commit has been added: https://github.com/inbo/gulltracking/pull/29/commits/a4b386ec5fcc63959c5b6e72f3ee8cbd8feb54ed

**Comment by peterdesmet** [comment]
Oh, my mistake, didn't know they were all valid. I wished all usethis action templates had a comment at the top mentioning their source to use this. :-)
